sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libbfd-dev 
    - libdw-dev
    - binutils-dev
language: rust
cache: cargo

rust:
  - nightly
  - stable

before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install git+https://github.com/FractalGlobal/travis-cargo.git@fix-coveralls --user &&
      export PATH=$HOME/.local/bin:$PATH
      fi

script:
  - |
      travis-cargo build &&
      travis-cargo test;

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo coveralls --no-sudo --verify; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

notifications:
  email: false