sudo: false
language: rust
rust:
  - nightly
  - stable
before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
  - |
    travis-cargo --only stable coveralls --no-sudo

notifications:
  email: false