[package]
name = "dataloader"
version = "0.8.1"
edition = "2018"
authors = ["cksac <cs.cksac@gmail.com>"]
description = "Rust implementation of Facebook's DataLoader using futures."
keywords = ["batcher", "dataloader", "cache"]
categories = ["asynchronous", "caching"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/cksac/dataloader-rs"
homepage = "https://github.com/cksac/dataloader-rs"
documentation = "https://docs.rs/dataloader"

[badges]
travis-ci = { repository = "/cksac/dataloader-rs" }

[dependencies]
futures = "0.3"
async-trait = "0.1"
async-std = { version = "1.0", features = ["unstable"] }

[dev-dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper", branch = "async-await", features = ["async"] }
fake = { version = "2.0", features = ["derive"] }
rand = "0.7.3"
async-graphql = "1.4.4"