[package]
name = "dataloader"
version = "0.6.0-dev"
edition = "2018"
authors = ["cksac <cs.cksac@gmail.com>"]
description = "Rust implementation of Facebook's DataLoader using futures and tokio."
keywords = ["batcher", "dataloader", "cache"]
categories = ["asynchronous", "caching"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/cksac/dataloader-rs"
homepage = "https://github.com/cksac/dataloader-rs"
documentation = "https://docs.rs/dataloader"

[badges]
travis-ci = { repository = "/cksac/dataloader-rs" }

[dependencies]
tokio = "0.1"

[dependencies.futures]
version = "0.3.0-alpha.16"
package = "futures-preview"
features = ["compat"]